# Generated by Django 4.2.16 on 2024-11-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_movies', '0003_likemovie'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_movie',
            field=models.ManyToManyField(related_name='liked_by_users', to='group_movies.likemovie'),
        ),
    ]
