# Generated by Django 4.2.16 on 2024-11-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='include_members',
        ),
    ]
