# Generated by Django 4.2.16 on 2024-11-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_img',
            field=models.ImageField(blank=True, default='', upload_to='group_images/'),
        ),
    ]
