# Generated by Django 4.2.16 on 2024-11-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_movies', '0002_alter_group_group_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_img',
            field=models.ImageField(blank=True, default='default/group.png', upload_to='group_images/'),
        ),
    ]
