# Generated by Django 4.2.16 on 2024-11-22 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_movies', '0003_alter_group_group_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='group_movies.groupmovie'),
        ),
    ]
