# Generated by Django 4.2.16 on 2024-11-23 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_movies', '0004_alter_article_group_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='group_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='group_movies.groupmovie'),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='group_movies.groupmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/%Y/%m/')),
                ('order', models.IntegerField(default=0)),
                ('group_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_img', to='group_movies.groupmovie')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='group_movies.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
