# Generated by Django 4.2.16 on 2024-11-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_movies', '0007_rename_post_articleimage_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='article_imges/'),
        ),
    ]
