# Generated by Django 4.2.16 on 2024-11-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_movies', '0008_alter_articleimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='user',
        ),
    ]
